AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Bucket:
    Type: String
  Key:
    Type: String
Resources:
  ShortenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          BUCKET: !Ref Bucket
          KEY: !Ref Key
      Events:
        GetAlias:
          Type: Api
          Properties:
            Path: "/{alias}"
            Method: get

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Description: "The URL of the deployed API Gateway endpoint"
